import type { Metadata } from "next";
import { Manrope } from "next/font/google";

const manrope = Manrope({
  weight: ["600", "800"],
  subsets: ["latin"],
});

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}  antialiased`}>{children}</body>
    </html>
  );
}
